In [62]:
import torch
import numpy as np

In [75]:
import torch
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')


In [20]:
X = torch.rand(2,3,dtype=torch.double)

In [21]:
X

tensor([[0.6469, 0.0742, 0.8955],
        [0.7888, 0.7484, 0.3898]], dtype=torch.float64)

In [24]:
# This code gives the data type of the tensor
print(X.type())

torch.DoubleTensor


In [25]:
# This code gives the size of the tensor
print(X.size())

torch.Size([2, 3])


#### DIFFERENT TYPES OF OPERATIONS

In [38]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [39]:
print(x)
print(y)

tensor([[0.5913, 0.5167],
        [0.4505, 0.0429]])
tensor([[0.2064, 0.1760],
        [0.0926, 0.3906]])


In [40]:
# This code adds two tensors
Z = x + y
print(Z)

tensor([[0.7977, 0.6928],
        [0.5431, 0.4334]])


In [41]:
y.add_(x) # this code will add the elements of y to x
print(y)
# we can do torch.add(x,y) also

tensor([[0.7977, 0.6928],
        [0.5431, 0.4334]])


In [42]:
# this code will substract the elements of y from x
y.sub_(x) # this is inplace operation
# we can also do this by torch.sub(x,y)

tensor([[0.2064, 0.1760],
        [0.0926, 0.3906]])

In [43]:
# this code will divide the elements of y with x
y.div_(x) # this is inplace operation
# we can also do this by torch.div(x,y)

tensor([[0.3490, 0.3406],
        [0.2055, 9.1105]])

In [44]:
# this code will multiply the elements of y with x
y.mul_(x) # this is inplace operation
# we can also do this by torch.mul(x,y)

tensor([[0.2064, 0.1760],
        [0.0926, 0.3906]])

In [45]:
# slicing operation of tensor
a = torch.rand(5,5)
print(a)

tensor([[0.5925, 0.6781, 0.1348, 0.5378, 0.7329],
        [0.7843, 0.2576, 0.3116, 0.0965, 0.4888],
        [0.3126, 0.6108, 0.9725, 0.6591, 0.7583],
        [0.6152, 0.0364, 0.0675, 0.0417, 0.7899],
        [0.7452, 0.8694, 0.1226, 0.2407, 0.4003]])


In [46]:
# get all rows of first columns numbers
print(a[:,0])

tensor([0.5925, 0.7843, 0.3126, 0.6152, 0.7452])


In [49]:
# get all columns of first row numbers
print(a[1,:])

tensor([0.7843, 0.2576, 0.3116, 0.0965, 0.4888])


#### Reshaping a Tensor

In [55]:
x = torch.rand(4,5)
print(x)

tensor([[0.2893, 0.0695, 0.8292, 0.7670, 0.2567],
        [0.5771, 0.4469, 0.3282, 0.0647, 0.8446],
        [0.3380, 0.2731, 0.2324, 0.7229, 0.7692],
        [0.2104, 0.1479, 0.8470, 0.4623, 0.3435]])


In [56]:
# using view to reshape the tensor x
y = x.view(20) # this will reshape into 1D tensor
print(y)

tensor([0.2893, 0.0695, 0.8292, 0.7670, 0.2567, 0.5771, 0.4469, 0.3282, 0.0647,
        0.8446, 0.3380, 0.2731, 0.2324, 0.7229, 0.7692, 0.2104, 0.1479, 0.8470,
        0.4623, 0.3435])


In [59]:
# convert into 5,4 dimensions
y = x.view(5,4)

In [60]:
print(y)

tensor([[0.2893, 0.0695, 0.8292, 0.7670],
        [0.2567, 0.5771, 0.4469, 0.3282],
        [0.0647, 0.8446, 0.3380, 0.2731],
        [0.2324, 0.7229, 0.7692, 0.2104],
        [0.1479, 0.8470, 0.4623, 0.3435]])


#### Tensors to Numpy array
One important thing is you have to be careful because if you change the tensor then the numpy array will also change

In [61]:
x = torch.ones(5)
print(x.type())

torch.FloatTensor


In [66]:
y = x.numpy()
print(type(y))

<class 'numpy.ndarray'>


In [67]:
# important thing
x.add_(1)

tensor([2., 2., 2., 2., 2.])

In [68]:
print(y)

[2. 2. 2. 2. 2.]


#### Numpy to Tensor

In [76]:
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [77]:
y = torch.from_numpy(x)
print(y)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [78]:
x = x+1

In [79]:
print(x)

[2. 2. 2. 2. 2.]


In [80]:
print(y)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
